/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.itn.librarymanagementsystem;

import com.itn.librarymanagementsystem.dao.BookDao;
import com.itn.librarymanagementsystem.dao.IssueBookDao;
import com.itn.librarymanagementsystem.dao.MemberDao;
import com.itn.librarymanagementsystem.entity.Book;
import com.itn.librarymanagementsystem.entity.IssueBook;
import com.itn.librarymanagementsystem.entity.Member;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author bijay
 */
public class IssueBookPanel extends javax.swing.JPanel {

    private static Member selectedMember = null;
    private static Book selectedBook = null;
    
    /**
     * Creates new form IssueBookPanel
     */
    public IssueBookPanel() {
        initComponents();
        loadData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new java.awt.Panel();
        titlePanel = new java.awt.Panel();
        issueBookLabel = new javax.swing.JLabel();
        selectBookLabel = new javax.swing.JLabel();
        selectMemberLabel = new javax.swing.JLabel();
        memberCB = new javax.swing.JComboBox<>();
        bookCB = new javax.swing.JComboBox<>();
        membershipTypeLabel = new javax.swing.JLabel();
        membershipCB = new javax.swing.JComboBox<>();
        editionLabel = new javax.swing.JLabel();
        editionField = new javax.swing.JTextField();
        issueDateLabel = new javax.swing.JLabel();
        issueDateField = new javax.swing.JTextField();
        returnDateField = new javax.swing.JTextField();
        returnDateLabel = new javax.swing.JLabel();
        confirmIssue = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(153, 255, 153));

        titlePanel.setBackground(new java.awt.Color(204, 204, 255));

        issueBookLabel.setFont(new java.awt.Font("Segoe Print", 1, 16)); // NOI18N
        issueBookLabel.setForeground(new java.awt.Color(255, 0, 51));
        issueBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        issueBookLabel.setText("Issue a Book");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(issueBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(issueBookLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        selectBookLabel.setBackground(new java.awt.Color(255, 255, 204));
        selectBookLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectBookLabel.setForeground(new java.awt.Color(0, 0, 0));
        selectBookLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectBookLabel.setText("Select Book");

        selectMemberLabel.setBackground(new java.awt.Color(255, 255, 204));
        selectMemberLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectMemberLabel.setForeground(new java.awt.Color(0, 0, 0));
        selectMemberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectMemberLabel.setText("Select Member");

        memberCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select a Member --", " " }));
        memberCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                memberCBItemStateChanged(evt);
            }
        });
        memberCB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberCBMouseClicked(evt);
            }
        });
        memberCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberCBActionPerformed(evt);
            }
        });

        bookCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select a Book --", " " }));
        bookCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookCBActionPerformed(evt);
            }
        });

        membershipTypeLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        membershipTypeLabel.setForeground(new java.awt.Color(0, 0, 0));
        membershipTypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        membershipTypeLabel.setText("Membership Type");

        membershipCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platinum Member", "Gold Member", "Silver Member", "General Member" }));
        membershipCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                membershipCBActionPerformed(evt);
            }
        });

        editionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editionLabel.setForeground(new java.awt.Color(0, 0, 0));
        editionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editionLabel.setText("Edition");

        editionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editionFieldActionPerformed(evt);
            }
        });

        issueDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        issueDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        issueDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        issueDateLabel.setText("Issuse Date");

        issueDateField.setText("YYYY-MM-DD");
        issueDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueDateFieldActionPerformed(evt);
            }
        });

        returnDateField.setText("YYYY-MM-DD");

        returnDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        returnDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        returnDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        returnDateLabel.setText("Return Date");

        confirmIssue.setBackground(new java.awt.Color(255, 255, 153));
        confirmIssue.setForeground(new java.awt.Color(255, 0, 0));
        confirmIssue.setText("Confirm Issue");
        confirmIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmIssueActionPerformed(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(memberCB, 0, 309, Short.MAX_VALUE)
                    .addComponent(selectMemberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(membershipTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(membershipCB, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueDateField)
                    .addComponent(issueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(editionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editionField, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bookCB, 0, 301, Short.MAX_VALUE)
                                .addComponent(selectBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(returnDateField))
                            .addComponent(confirmIssue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectMemberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectBookLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberCB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookCB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(membershipTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(membershipCB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editionField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirmIssue, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void membershipCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_membershipCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_membershipCBActionPerformed

    private void memberCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberCBActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_memberCBActionPerformed

    private void bookCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookCBActionPerformed

    private void editionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editionFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void issueDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueDateFieldActionPerformed

    private void confirmIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmIssueActionPerformed
        // TODO add your handling code here:
        Member member = new Member();
        Book book = new Book();
        IssueBook issue = new IssueBook();
        
        String selectedMember = String.valueOf(memberCB.getSelectedItem());
        int memberId = Integer.parseInt(selectedMember.substring(selectedMember.lastIndexOf("/") + 1));
        
        String selectedBook = String.valueOf(bookCB.getSelectedItem());
        int bookId = Integer.parseInt(selectedBook.substring(selectedBook.lastIndexOf("/") + 1));
        
        issue.setMemberId(memberId);
        issue.setBookId(bookId);
        issue.setEdition(editionField.getText());
        issue.setIssueDate(Date.valueOf(issueDateField.getText()));
        issue.setReturnDate(Date.valueOf(returnDateField.getText()));
        
        member.setId(memberId);
        book.setId(bookId);
        boolean success = new IssueBookDao().issueBook(issue, member, book);
        if(success){
            JOptionPane.showMessageDialog(this, "Book issued successfully!");
        }
        else{
            JOptionPane.showMessageDialog(this, "Book cannot be added!");
        }
        
    }//GEN-LAST:event_confirmIssueActionPerformed

    private void memberCBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberCBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_memberCBMouseClicked

    private void memberCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_memberCBItemStateChanged
        // TODO add your handling code here:
        String id = String.valueOf(memberCB.getSelectedItem());
        int memberId = Integer.parseInt(id.substring(id.lastIndexOf("/")+1));
        
        selectedMember = new MemberDao().getMemberById(memberId);
        String memType = selectedMember.getMembershipType();
        membershipCB.setSelectedItem(memType);
        membershipCB.repaint();
        memberCB.hidePopup();
    }//GEN-LAST:event_memberCBItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bookCB;
    private javax.swing.JButton confirmIssue;
    private javax.swing.JTextField editionField;
    private javax.swing.JLabel editionLabel;
    private javax.swing.JLabel issueBookLabel;
    private javax.swing.JTextField issueDateField;
    private javax.swing.JLabel issueDateLabel;
    private javax.swing.JButton jButton1;
    private java.awt.Panel mainPanel;
    private javax.swing.JComboBox<String> memberCB;
    private javax.swing.JComboBox<String> membershipCB;
    private javax.swing.JLabel membershipTypeLabel;
    private javax.swing.JTextField returnDateField;
    private javax.swing.JLabel returnDateLabel;
    private javax.swing.JLabel selectBookLabel;
    private javax.swing.JLabel selectMemberLabel;
    private java.awt.Panel titlePanel;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
       ArrayList<Book> books = new BookDao().getAllBooks();
       ArrayList<Member> members = new MemberDao().getAllMembers();
       
       for(Book book:books){
           bookCB.addItem(book.getName()+ "/" + book.getId());
       }
       for(Member member:members){
           memberCB.addItem(member.getFirstName()+ " " + member.getLastName()+ "/" + member.getId());
       }
    }
}
