/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.itn.librarymanagementsystem;

import com.itn.librarymanagementsystem.dao.MemberDao;
import com.itn.librarymanagementsystem.entity.Member;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class UserPanel extends javax.swing.JPanel {

    /**
     * Creates new form UserPanel
     */
    
    private ArrayList<Member> memberList;
    private Member selectedMember;
    private boolean editMember;
    
    // Constructor 
    public UserPanel() {
        initComponents();
        
        // My codes
        
        memberList = new MemberDao().getAllMembers();
        
        Object[][] data = new Object[memberList.size()][10];
        String[] header = {"ID", "First Name", "Middle Name", "Last Name", "Address", "Email", "Phone Number","Gender", "Interest", "Membership Type"};
        int count = 0;
        for(Member m : memberList){
            data[count] = new Object[]{m.getId(),
                                       m.getFirstName(),
                                       m.getMidName(),
                                       m.getLastName(),
                                       m.getAddress(),
                                       m.getEmail(), 
                                       m.getPhoneNo(),
                                       m.getGender(),
                                       m.getInterest(),
                                       m.getMembershipType()};
            count++;
        }
        
        memberTable.setModel(new DefaultTableModel(data, header));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        addMemberLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        firstNameLabel = new javax.swing.JLabel();
        fNameField = new javax.swing.JTextField();
        midNameLabel = new javax.swing.JLabel();
        midNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        inputAddress = new javax.swing.JTextField();
        phLabel = new javax.swing.JLabel();
        inputPhone = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        buttonMale = new javax.swing.JRadioButton();
        buttonFemale = new javax.swing.JRadioButton();
        buttonOthers = new javax.swing.JRadioButton();
        interestLabel = new javax.swing.JLabel();
        checkboxAcademic = new javax.swing.JCheckBox();
        checkboxLiterature = new javax.swing.JCheckBox();
        checkboxReligion = new javax.swing.JCheckBox();
        checkboxST = new javax.swing.JCheckBox();
        membershipLabel = new javax.swing.JLabel();
        comboboxMembership = new javax.swing.JComboBox<>();
        addMemberButton = new javax.swing.JButton();
        memberPanel = new javax.swing.JPanel();
        displayLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();
        editButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Member Management");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addMemberLabel.setBackground(new java.awt.Color(255, 255, 153));
        addMemberLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addMemberLabel.setForeground(new java.awt.Color(255, 0, 0));
        addMemberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addMemberLabel.setText("Add New Member Detail");
        addMemberLabel.setToolTipText("");
        addMemberLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMemberLabel.setOpaque(true);

        firstNameLabel.setText("First name");

        fNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameFieldActionPerformed(evt);
            }
        });

        midNameLabel.setText("Middle name");

        lastNameLabel.setText("Last name");

        addressLabel.setText("Address");

        phLabel.setText("Phone no:");

        emailLabel.setText("Email");

        genderLabel.setText("Gender");

        genderGroup.add(buttonMale);
        buttonMale.setText("Male");
        buttonMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMaleActionPerformed(evt);
            }
        });

        genderGroup.add(buttonFemale);
        buttonFemale.setText("Female");

        genderGroup.add(buttonOthers);
        buttonOthers.setText("Others");
        buttonOthers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOthersActionPerformed(evt);
            }
        });

        interestLabel.setText("Interest");

        checkboxAcademic.setText("Acadamic");
        checkboxAcademic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxAcademicActionPerformed(evt);
            }
        });

        checkboxLiterature.setText("Literature");

        checkboxReligion.setText("Religion");

        checkboxST.setText("Science & Technology");

        membershipLabel.setText("Membership");

        comboboxMembership.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platinum Member", "Gold Member", "Silver Member", "General Member" }));

        addMemberButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addMemberButton.setForeground(new java.awt.Color(255, 0, 0));
        addMemberButton.setText("Add Member");
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(membershipLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                    .addComponent(interestLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(phLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addressLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(inputEmail))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(buttonMale)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(buttonFemale)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(buttonOthers))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(comboboxMembership, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(checkboxAcademic)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(checkboxLiterature)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(checkboxReligion)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(checkboxST)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(inputAddress)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(midNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(midNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 61, Short.MAX_VALUE)))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(addMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addMemberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addMemberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(fNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midNameLabel)
                    .addComponent(midNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(emailLabel)
                        .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(buttonMale)
                    .addComponent(buttonFemale)
                    .addComponent(buttonOthers))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(interestLabel)
                    .addComponent(checkboxAcademic)
                    .addComponent(checkboxLiterature)
                    .addComponent(checkboxReligion)
                    .addComponent(checkboxST))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(membershipLabel)
                    .addComponent(comboboxMembership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        memberPanel.setBackground(new java.awt.Color(153, 255, 153));

        displayLabel.setBackground(new java.awt.Color(255, 255, 153));
        displayLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        displayLabel.setForeground(new java.awt.Color(255, 0, 0));
        displayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        displayLabel.setText("Display All Members");
        displayLabel.setToolTipText("");
        displayLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        displayLabel.setOpaque(true);

        jSeparator2.setOpaque(true);

        memberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        memberTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(memberTable);

        editButton.setBackground(new java.awt.Color(255, 255, 153));
        editButton.setForeground(new java.awt.Color(255, 0, 51));
        editButton.setText("Edit Record");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Delete Record");

        javax.swing.GroupLayout memberPanelLayout = new javax.swing.GroupLayout(memberPanel);
        memberPanel.setLayout(memberPanelLayout);
        memberPanelLayout.setHorizontalGroup(
            memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(memberPanelLayout.createSequentialGroup()
                        .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(memberPanelLayout.createSequentialGroup()
                                .addComponent(displayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(memberPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(editButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        memberPanelLayout.setVerticalGroup(
            memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(displayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(memberPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameFieldActionPerformed

    private void buttonMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMaleActionPerformed

    private void buttonOthersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOthersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOthersActionPerformed

    private void checkboxAcademicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxAcademicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkboxAcademicActionPerformed

    private void addMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberButtonActionPerformed
        // add member button: collect data from form
        if(!editMember){
        Member member = new Member();
        member.setFirstName(fNameField.getText());
        member.setLastName(lastNameField.getText());
        member.setMidName(midNameField.getText());
        member.setAddress(inputAddress.getText());
        member.setEmail(inputEmail.getText());
        member.setPhoneNo(inputPhone.getText());
        member.setMembershipType(String.valueOf(comboboxMembership.getSelectedItem()));
        
        
        // for radio buttons
        if(buttonMale.isSelected())
            member.setGender("MALE");
        else if(buttonFemale.isSelected())
            member.setGender("FEMALE");
        else
            member.setGender("OTHERS");
        
        // for Checkbox
        String interest = "";
        if(checkboxAcademic.isSelected())
            interest = interest.concat("ACADAMIC ");
        else if(checkboxLiterature.isSelected())
            interest = interest.concat("Literature ");
        else if(checkboxReligion.isSelected())
            interest = interest.concat("Religion ");
        else if(checkboxST.isSelected())
            interest = interest.concat("Science & Technology");
        member.setInterest(interest);
        
        boolean success = new MemberDao().addMember(member);
        if(success){
            JOptionPane.showMessageDialog(this, "Member added successfully! ");
        }
        else{
            JOptionPane.showMessageDialog(this, "Member cannot be added");
        }
        }
        
        // save data collected to a  database table..
        
        // show appropriate message..
        
    }//GEN-LAST:event_addMemberButtonActionPerformed

    private void memberTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberTableMouseClicked
        // TODO add your handling code here:
        
        int row = memberTable.getSelectedRow();
        int column = memberTable.getSelectedColumn();
        
        System.out.println("Row selected: " + memberList.get(row).getFirstName());
        selectedMember = memberList.get(row);
        
        
        
    }//GEN-LAST:event_memberTableMouseClicked

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        
        if(selectedMember == null){
            JOptionPane.showMessageDialog(this, "No record selected");
        }
        else{
            clearForm();
            addMemberButton.setText("Submit");
            fNameField.setText(selectedMember.getFirstName());
            midNameField.setText(selectedMember.getMidName());
            lastNameField.setText(selectedMember.getLastName());
            inputAddress.setText(selectedMember.getAddress());
            inputPhone.setText(selectedMember.getPhoneNo());
            inputEmail.setText(selectedMember.getEmail());
            
            switch(selectedMember.getGender()){
                case "MALE" -> buttonMale.setSelected(true);
                case "FEMALE" -> buttonFemale.setSelected(true);
                default -> buttonOthers.setSelected(true);
            }
            
            String interest = selectedMember.getInterest();
            if(interest.contains("ACADEMIC")){
                checkboxAcademic.setSelected(true);
            }
            if(interest.contains("Religion")){
                checkboxReligion.setSelected(true);
            }
            if(interest.contains("Literature")){
                checkboxLiterature.setSelected(true);
            }
            if(interest.contains("Science & Technology")){
                checkboxST.setSelected(true);
            }
            comboboxMembership.setSelectedItem(selectedMember.getMembershipType());
            
        }
        
    }//GEN-LAST:event_editButtonActionPerformed
    public void clearForm(){
    
    buttonFemale.setSelected(false);
    buttonMale.setSelected(false);
    buttonOthers.setSelected(false);
    checkboxAcademic.setSelected(false);
    checkboxLiterature.setSelected(false);
    checkboxReligion.setSelected(false);
    checkboxST.setSelected(false);
    comboboxMembership.setSelectedIndex(0);
    fNameField.setText("");
    inputAddress.setText("");
    inputEmail.setText("");
    inputPhone.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMemberButton;
    private javax.swing.JLabel addMemberLabel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JRadioButton buttonFemale;
    private javax.swing.JRadioButton buttonMale;
    private javax.swing.JRadioButton buttonOthers;
    private javax.swing.JCheckBox checkboxAcademic;
    private javax.swing.JCheckBox checkboxLiterature;
    private javax.swing.JCheckBox checkboxReligion;
    private javax.swing.JCheckBox checkboxST;
    private javax.swing.JComboBox<String> comboboxMembership;
    private javax.swing.JLabel displayLabel;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField fNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JLabel interestLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JPanel memberPanel;
    private javax.swing.JTable memberTable;
    private javax.swing.JLabel membershipLabel;
    private javax.swing.JTextField midNameField;
    private javax.swing.JLabel midNameLabel;
    private javax.swing.JLabel phLabel;
    // End of variables declaration//GEN-END:variables
}
