spring.application.name=TodoApp
spring.datasource.url=jdbc:mysql://localhost:3306/todo_app
spring.datasource.username=root
spring.datasource.password=CallMeRonaldo@7

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true